const CREATE = 'CREATE';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_SEARCHES = 'FETCH_SEARCHES';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const LIKE = 'LIKE';
const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

export {
	AUTH,
	CREATE,
	DELETE,
	FETCH_ALL,
	FETCH_SEARCHES,
	LIKE,
	LOGOUT,
	UPDATE,
};
