const CREATE = 'CREATE';
const FETCH_POST = 'FETCH_POST';
const FETCH_ALL = 'FETCH_ALL';
const FETCH_SEARCHES = 'FETCH_SEARCHES';
const UPDATE = 'UPDATE';
const DELETE = 'DELETE';
const LIKE = 'LIKE';

const START_LOADING = 'START_LOADING';
const END_LOADING = 'END_LOADING';

const AUTH = 'AUTH';
const LOGOUT = 'LOGOUT';

export {
  AUTH,
  CREATE,
  DELETE,
  END_LOADING,
  FETCH_ALL,
  FETCH_POST,
  FETCH_SEARCHES,
  LIKE,
  LOGOUT,
  START_LOADING,
  UPDATE,
};
